name: Benchmark JSONPath

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
  push:
    branches:
      - main
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install requirements
        run: pip install j2cli

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build -v ./...

      - name: Benchmark `$.store.book[0].price`
        run: go test -benchmem -bench Benchmark_threeLevelsWithIndex > benchmark_threeLevelsWithIndex_test.result.txt

      - name: Benchmark `$..book[?(@.price > $.store.bicycle.price)]`
        run: go test -benchmem -bench Benchmark_recursiveDescentWithFilter > benchmark_recursiveDescentWithFilter_test.result.txt

      - name: Update README
        run: j2 -o README.md assets/README.t

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'update README for ${{ github.sha }}'
